### ISSUE TITLE
are you using a special branch/commit for meta-dataset from the google repo (tf)?

### ISSUE THREAD

**Issue by brando90** [brando90/pytorch-meta-dataset#10]
https://github.com/brando90/meta-dataset/tree/master 

this is my fork. Want to put it in the gitsubmodules.

**Comment by patricks-lab** [comment]
No when I installed google's mds I used the newest commit (which should just be the current one [ca81edb]).

**Comment by brando90** [comment]
thanks for specifying the exact commit!
