### ISSUE TITLE
need exact urls for imagnet

### ISSUE THREAD

**Issue by brando90** [brando90/pytorch-meta-dataset#2]
download_mds.sh needs urls for zipstars:
```

# -- ilsvrc_2012
# Download ilsvrc2012_img_train.tar, from the ILSVRC2012 website
# todo: https://gist.github.com/bonlime/4e0d236cf98cd5b15d977dfa03a63643
# todo: https://github.com/google-research/meta-dataset/blob/main/doc/dataset_conversion.md#ilsvrc_2012

# wget TODO -O $MDS_DATA_PATH/ilsvrc_2012
```

@patricks-lab 

feel free to put them in the download_mds.sh script I am making if you want

**Comment by patricks-lab** [comment]
I recall when I had downloaded imagenet I had to fill a form agreement. https://image-net.org/download.php  It should be quick and auto allows access after you sign up with a .edu account if I recall then it should give you download links to the needed tar files

**Comment by brando90** [comment]
@patricks-lab it wants Download ilsvrc2012_img_train.tar but I only see the whole one...what url did you use? can you send it to me?

**Comment by brando90** [comment]
wget https://image-net.org/data/winter21_whole.tar.gz ...
