### ISSUE TITLE
what path did you use for mds?

### ISSUE THREAD

**Issue by brando90** [brando90/pytorch-meta-dataset#3]
I was going to use this one:
```
mdkdir -p $HOME/mds
export MDS_DATA_PATH=$HOME/data/mds
```

see ouir download_mds.sh script.

**Comment by brando90** [comment]
@patricks-lab

**Comment by patricks-lab** [comment]
I think any empty folder is fine to put mds in, for example in my server I kept it in /shared/rsaas/pzy2 not sure if that helps? (I don’t recall that mds has a specific requirement for where you install your stuff as long as it can hold 200gbs of data)

**Comment by brando90** [comment]
> I think any empty folder is fine to put mds in, for example in my server I kept it in /shared/rsaas/pzy2 not sure if that helps? (I don’t recall that mds has a specific requirement for where you install your stuff as long as it can hold 200gbs of data)

if you look at all my code it always uses ~/data /dataset

I thought thats what you were doing...is it not? What exactly are you doing. I need to know for my data to work with your mains. 
@patricks-lab

**Comment by patricks-lab** [comment]
I put it in /shared/rsaas/pzy2 since it was too big for it to fit in data when I first tried it (and shared is a different partition)… basically check the episodic and batch loader python files and note in the mds args that I state that the data path is /shared/rsaas/pzy2. Change that to whatever you use as your data path if you’re not using the UIUC cluster I assume (if you are still using UIUC cluster just keep it since I already have a working copy of mds there)

**Comment by brando90** [comment]
ok u didn't use the /shared/rsaas/pzy2/data. I usually change where $HOME points to.

**Comment by brando90** [comment]
> basically check the episodic and batch loader python files and note in the mds args that I state that the data path is /shared/rsaas/pzy2

add the python command you ran and have this be an args in the python command.

**Comment by patricks-lab** [comment]
Yeah batchloader is this command https://github.com/brando90/diversity-for-predictive-success-of-meta-learning/blob/main/div_src/diversity_src/dataloaders/metadataset_batch_loader.py and episodic loader is this https://github.com/brando90/diversity-for-predictive-success-of-meta-learning/blob/main/div_src/diversity_src/dataloaders/metadataset_episodic_loader.py and I put the data path in a argumentparser object called —data_path (it should be /shared/rsaas/pzy2, replace that with whatever you have as your data path)
