### ISSUE TITLE
what is the $SPLITS and $RECORDS env vars?

### ISSUE THREAD

**Issue by brando90** [brando90/pytorch-meta-dataset#4]
the instructions the other ppl wrote but they don't provide what they are:
```
# -- omniglot
wget https://github.com/brendenlake/omniglot/raw/master/python/images_background.zip -O $MDS_DATA_PATH/omniglot
wget https://github.com/brendenlake/omniglot/raw/master/python/images_evaluation.zip -O $MDS_DATA_PATH/omniglot

# what is
#   --splits_root=$SPLITS \
  #  --records_root=$RECORD

python -m meta_dataset.dataset_conversion.convert_datasets_to_records \
  --dataset=omniglot \
  --omniglot_data_root=$DATASRC/omniglot \
  --splits_root=$SPLITS \
  --records_root=$RECORDS
```

https://github.com/google-research/meta-dataset/blob/main/doc/dataset_conversion.md#omniglot

(fyi, my reasoning for making the download_mds.sh script is also this, since I am running the commands anyway why not record them anyway? going to run them anwyay might as well document them, hopefully they work for others) @patricks-lab

**Comment by brando90** [comment]
I see these env vars are present everywhere in the instruction: https://github.com/google-research/meta-dataset/blob/main/doc/dataset_conversion.md#aircraft 

would be good to clarify them to clarify everything.

**Comment by patricks-lab** [comment]
I usually organize my files as following:

Mds  has sub folders records/ and splits/

They should be empty before you download mds, so just set $RECORDS to records/ and $SPLITS to splits/. Basicly mds puts the tfrecords to records and the heiarchical class splits to splits/.  But any empty folder should be sufficient for both enviro vars

**Comment by brando90** [comment]
ok I wil add:
```
export $RECORDS=records
export $SPLITS=splits
```

if that is right let me know and close issue :)

**Comment by patricks-lab** [comment]
Actually I think it should be the full path.. eg something like export $SPLITS=/home/brando/mds/splits and $RECORDS=/home/brando/mds/records (where mds is your designated mds data folder)

**Comment by brando90** [comment]
this?
```
export RECORDS=$MDS_DATA_PATH/records
export SPLITS=$MDS_DATA_PATH/splits
```

**Comment by brando90** [comment]
so it should be the same accross all data sets?

**Comment by patricks-lab** [comment]
Yeah that works, and yes it’s the same across all datasets . Basically each dataset will create a folder in records and a json file in splits if all goes well
