### ISSUE TITLE
why do we need gsutils?

### ISSUE THREAD

**Issue by brando90** [brando90/pytorch-meta-dataset#9]
https://github.com/brando90/pytorch-meta-dataset/blob/hdb/download_mds.sh#L7 

try to make comments self contained if possible

**Comment by patricks-lab** [comment]
You need gsutil to install the quickdraw dataset: (https://github.com/google-research/meta-dataset/blob/main/doc/dataset_conversion.md#quickdraw)

Try pip installing gsutil to see if that works but if not, I'm not sure which OS your server is but they have system-specific instructions to install gsutil here: https://download.huihoo.com/google/gdgdevkit/DVD1/developers.google.com/storage/docs/gsutil_install.html

**Comment by brando90** [comment]
@patricks-lab ok! So I will add it as a requirement to meta-data set in our hdb branch. Weird the original google authors didn't put it.
